orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: rohitlavu/app
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
  python-publisher: 
    environment:
      IMAGE_NAME: rohitlavu/app
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/python:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD


jobs:
    docker_build_and_push: 
      executor: docker-publisher
 
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker build -t $IMAGE_NAME:${CIRCLE_SHA1:0:7} .
              docker push $IMAGE_NAME:${CIRCLE_SHA1:0:7}
    deploy_to_kubernetes: 
      executor: python-publisher
 
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: install deps
            command: |
              pip install ruamel.yaml
              pip install GitPython 
        - run: 
            name: update manifests
            command: |
              python3 manifest_git_client.py


workflows:
  version: 2
  build-main:
    jobs:
      - docker_build_and_push
      - deploy_to_kubernetes:
          name: Staging Deploy
          requires:
            - docker_build_and_push
      - test_app_prod_hold:
          type: approval
          requires:
            - Staging Deploy
      - deploy_to_kubernetes:
          name: Prod Deploy
          requires:
            - test_app_prod_hold              
                 
             
    
       
      


    
           
   
    

    
