on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [assigned, opened, synchronize, reopened, editied]

jobs:
  jira:
    runs-on: ubuntu-latest
    name: Validate Jira ID from PR title
    steps:
      - uses: actions/checkout@v2
      - name: Enforce Jira Issue Key in Pull Request Title
        uses: ./ci/jira
        with:
          jira-host: ${{ secrets.JIRAHOST }}
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-api-token: ${{ secrets.JIRA_APITOKEN }}